Repository ros2/launch_ros, pull requests merged in 2019-08, with the labels that each got.

#40 Support xml and yaml files in ros2launch
  ros2launch/ros2launch/api/__init__.py
  ros2launch/ros2launch/api/api.py
  ros2launch/ros2launch/command/launch.py
Labels: enhancement, in progress

#51 Use node namespace if no other was specified
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/actions/push_ros_namespace.py
  test_launch_ros/test/test_launch_ros/actions/test_push_ros_namespace.py
Labels: in review

#62 install package marker and manifest
  launch_ros/resource/launch_ros
  launch_ros/setup.py
Labels: bug, in review

#63 [backport-dashing] install package marker and manifest (#62)
  launch_ros/resource/launch_ros
  launch_ros/setup.py
Labels: bug, in review
