Repository ros2/launch_ros, pull requests merged in 2019-05, with the labels that each got.

#20 use local import
  launch_testing_ros/launch_testing_ros/message_pump.py
Labels: bug, in review

#21 Corrected matches_action usage in lifecycle_pub_sub example
  launch_ros/examples/lifecycle_pub_sub_launch.py
Labels: bug, in review

#24 Launch autocomplete doesnt require dot
  ros2launch/ros2launch/api/api.py
Labels: in review

#25 Fix deprecation warnings
  launch_ros/launch_ros/actions/lifecycle_node.py
  launch_testing_ros/examples/talker_listener.test.py
  launch_testing_ros/launch_testing_ros/data_republisher.py
Labels: in progress

#26 Add custom LaunchTestRunner with ROS specific preamble
  launch_testing_ros/launch_testing_ros/__init__.py
  launch_testing_ros/launch_testing_ros/test_runner.py
Labels: in review

#27 fix calling of print_arguments_of_launch_description()
  ros2launch/ros2launch/api/api.py
Labels: bug, in review

#28 fix example test logic
  launch_testing_ros/examples/talker_listener.test.py
Labels: bug, in review

#31 Parameter values get evaluated by yaml rules
  launch_ros/launch_ros/utilities/evaluate_parameters.py
  test_launch_ros/test/test_launch_ros/test_normalize_parameters.py
Labels: in review
