Repository ros2/launch_ros, pull requests merged in 2020-08, with the labels that each got.

#137 Fix problems when parsing a `Command` `Substitution` as a parameter value
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/descriptions/__init__.py
  launch_ros/launch_ros/parameter_descriptions.py
  launch_ros/launch_ros/parameters_type.py
  launch_ros/launch_ros/utilities/evaluate_parameters.py
  launch_ros/launch_ros/utilities/normalize_parameters.py
  test_launch_ros/test/test_launch_ros/actions/test_node.py
  test_launch_ros/test/test_launch_ros/actions/test_set_parameter.py
  test_launch_ros/test/test_launch_ros/descriptions/test_parameter.py
  test_launch_ros/test/test_launch_ros/frontend/test_node_frontend.py
Labels: in review

#168 Substitutions in parameter files
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/descriptions/__init__.py
  launch_ros/launch_ros/parameter_descriptions.py
  launch_ros/launch_ros/parameters_type.py
  launch_ros/launch_ros/utilities/evaluate_parameters.py
  launch_ros/launch_ros/utilities/normalize_parameters.py
  test_launch_ros/test/test_launch_ros/descriptions/test_parameter_file.py
Labels: enhancement, in review

#166 Fix race with launch context changes when loading composable nodes
  launch_ros/launch_ros/actions/load_composable_nodes.py
  test_launch_ros/test/test_launch_ros/actions/test_load_composable_nodes.py
Labels: bug

#173 Fix case where list of composable nodes is zero
  launch_ros/launch_ros/actions/composable_node_container.py
  test_launch_ros/test/test_launch_ros/actions/test_composable_node_container.py
Labels: bug

#174 Asynchronously wait for load node service response
  launch_ros/launch_ros/actions/load_composable_nodes.py
Labels: bug
